#!/bin/sh

exercism download --exercise="$1" --track=cpp

slug_name="$1"
file_name="${1//-/_}"
def_name="$(echo $file_name | tr '[:lower:]' '[:upper:]')_H"

cd "$slug_name"

echo "#ifndef $def_name
#define $def_name

namespace $file_name {

}

#endif" > $file_name.h

echo "#include \"$file_name.h\"

using namespace std;

" > $file_name.cpp

mkdir build
cd build
cmake -G 'Unix Makefiles' ..
