// Generated by CoffeeScript 1.12.7
(function() {
  var Prime;

  Prime = (function() {
    var divisors, is_prime, prime_gen, primes;

    function Prime() {}

    primes = [];

    Prime.nth = function(n) {
      var p, ref;
      if (n > primes.length) {
        ref = prime_gen();
        for (p of ref) {
          primes.push(p);
          if (n >= primes.length) {
            break;
          }
        }
      }
      return primes[n - 1];
    };

    prime_gen = function*() {
      var i, results;
      i = 2;
      results = [];
      while (true) {
        if (is_prime(i)) {
          yield i;
        }
        results.push(i += 1);
      }
      return results;
    };

    is_prime = function(n) {
      return divisors(n) === '1' + n;
    };

    divisors = function(n) {
      var i;
      return ((function() {
        var j, ref, results;
        results = [];
        for (i = j = 1, ref = n; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
          if (n % i === 0) {
            results.push(i);
          }
        }
        return results;
      })()).join('');
    };

    return Prime;

  })();

  module.exports = Prime;

}).call(this);
